Auctions_Project/auctions/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create", views.create, name="create"),
    path("listing/<int:listingID>", views.listing, name="listing"),
    path("watch", views.watch, name="watch"),
    path("categories", views.category, name="category"),
    path("add_watchlist/<int:listingID>", views.add_watchlist, name="add_watchlist"),
    path("remove_watchlist/<int:listingID>", views.remove_watchlist, name="remove_watchlist"),
    path("close_listing/<int:listingID>", views.close_listing, name="close_listing")
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Auctions_Project/commerce/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("auctions.urls"))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Auctions_Project/auctions/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class User(AbstractUser):
    pass




# Auctions listings models for handling items data
class AuctionListing(models.Model):
    CATEGORY_CHOICES = [
        ("FD", "Foods"),
        ("ET", "Entertainment"),
        ("LS", "LifeStyle"),
        ("CL", "Clothing"),
        ("HL", "Halal Category"),
        ("DL", "Daily Essentials"),
        ("TD", "Trendings"),
        ("TE", "Techno")
    ]

    name = models.CharField(max_length=64)
    price = models.DecimalField(max_digits=10 ,decimal_places=2)
    description = models.TextField(blank=True)
    creator = models.ForeignKey(User, on_delete=models.CASCADE, related_name="auction_creator")
    time = models.DateTimeField(auto_now_add=True)
    pic = models.ImageField(upload_to="auctionPics/", blank=True, null=True)
    category = models.CharField(max_length=2, choices=CATEGORY_CHOICES)
    auction_active = models.BooleanField(default=True)
    highest_bid = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    def total_bids(self):
        return self.bids.count() # type: ignore

    # Showing what will be displayed when user access data
    def __str__(self) -> str:
        return f"Auction Id: {self.id} :: Name: {self.name} :: Price: {self.price} :: Date: {self.time}" # type: ignore
    

    

# Bidding model which handles all the bids made on auction listing
class Bid(models.Model):
    bid = models.DecimalField(max_digits=10, decimal_places=2)
    bidder = models.ForeignKey(User, on_delete=models.CASCADE, related_name="bids")
    auction = models.ForeignKey(AuctionListing, on_delete=models.CASCADE, related_name="bids")

    # Showing what will be displated when user places and accesses a bid
    def __str__(self) -> str:
        return f"Bid Id: {self.id} :: Name: {self.auction} :: Price: {self.bid}" # type: ignore
    



# Comments Model for handling all the data users made on comments
class Comment(models.Model):
    auction = models.ForeignKey(AuctionListing, on_delete=models.CASCADE, related_name="auction_name")
    commenter = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comment_name")
    content = models.TextField()
    
    # Showing my commenter name
    def __str__(self) -> str:
        return f"Commentor Id: {self.id} :: Name: {self.commenter} :: Auction: {self.auction}" # type: ignore




# Watchlist model for handling if a user has put certain auctions on saving
class Watchlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="watchlist_user")
    auction = models.ForeignKey(AuctionListing, on_delete=models.CASCADE, related_name="watchlist_auction")

    # Showing the watchlists
    def __str__(self) -> str:
        return f"User: {self.user} Auction: {self.auction}"
    

Auctions_Project/auctions/forms.py
from django import forms
from .models import AuctionListing, Bid, Comment


# Models form for my auction lisings
class AuctionListingForm(forms.ModelForm):
    class Meta:
        model = AuctionListing
        fields = ["name", "price", "category", "description", "pic"]
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-light", "label": "Auction Name"}),
            "price": forms.NumberInput(attrs={"class": "form-medium"}),
            "category": forms.Select(attrs={"class": "form-dark"}),
            "description": forms.Textarea(attrs={"class": "form-text-area", "rows": 4, "columns": 40}),
            "pic": forms.ClearableFileInput(attrs={"class": "form-pic"}),
        }




# Models form my auction biddings
class BidForm(forms.ModelForm):
    class Meta:
        model = Bid
        fields = ["bid"]
        widgets = {
            "bid": forms.NumberInput(attrs={"class": "listing-content-main", "id": "bidCommentForm", "placeholder": "What's Your Limit!"})
        }




# Models form for my comments on auctions
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["content"]
        widgets = {
            "content": forms.Textarea(attrs={"class": "listing-content-main", "id": "bidCommentForm"})
        }

Auctions_Project/auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse

from .forms import AuctionListingForm, BidForm, CommentForm
from .models import User, AuctionListing, Bid, Comment, Watchlist


def index(request):

    # Getting all the data from the database model
    listings = AuctionListing.objects.all()

    # Returning the data to the template
    return render(request, "auctions/index.html", {
        "listings": listings
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]

        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "auctions/register.html", {
                "message": "Passwords must match."
            })

        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()
        except IntegrityError:
            return render(request, "auctions/register.html", {
                "message": "Username already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("index"))
    else:
        return render(request, "auctions/register.html")


# Function when someone wanna create something
@login_required(login_url="login")
def create(request):

    # Checking if user submitted form AKA POST
    if request.method == "POST":

        form = AuctionListingForm(request.POST, request.FILES)

        # Checking if data is valid
        if form.is_valid():

            # Not commiting to the database yet for manipulation
            auction_listings = form.save(commit=False)

            # Adding the current user to the data set
            auction_listings.creator = request.user

            # Now saving the data
            auction_listings.save()

            # redirect user to default page
            return redirect("index")
        
    # If user got here through GET   
    else: 
        form = AuctionListingForm()

    return render(request, "auctions/create.html", {
        "form": form
    })


# Function when someone accesses a certain listing by clicking it
@login_required(login_url="login")
def listing(request, listingID):

    # First getting the data and forms ready
    current_listing = get_object_or_404(AuctionListing, pk = listingID) 
    bid_form = BidForm()
    comment_form = CommentForm()
    total_bids = current_listing.total_bids()
    is_creator = False
    is_in_watchlist = False

    # Checking the current user is the creator
    if request.user == current_listing.creator:
        is_creator = True

    # Checking if the bid exists in the watchlist
    if Watchlist.objects.filter(user = request.user, auction = current_listing).exists():
        is_in_watchlist = True

    # Setting the highest bidder as none
    highest_bidder = None

    # Checking if the listings has a highest bidding
    if current_listing.highest_bid:
        highest_bid = Bid.objects.get(bid = current_listing.highest_bid, auction = current_listing)
        highest_bidder = highest_bid.bidder

    # If user submitted any kind of form then
    if request.method == "POST":

        # Checking if the user submitted someone kind of bid
        if "bid" in request.POST:

            # Getting all the data from post
            bid_form = BidForm(request.POST)

            # Checking if data is valid
            if bid_form.is_valid():

                # Temporarily saving the bid
                new_bid = bid_form.save(commit = False)

                # Now making checks if bid meets requirements
                if new_bid.bid > current_listing.price and (current_listing.highest_bid is None or new_bid.bid > current_listing.highest_bid):
                    
                    # Setting the new parameters of new bid
                    new_bid.bidder = request.user
                    new_bid.auction = current_listing
                    new_bid.save()

                    # Now setting the highest bid
                    current_listing.highest_bid = new_bid.bid
                    current_listing.save()

                    if current_listing.highest_bid:
                        highest_bid = Bid.objects.get(bid = current_listing.highest_bid, auction = current_listing)
                        highest_bidder = highest_bid.bidder

                    total_bids = current_listing.total_bids()


                    # Rendering appropriate data
                    return render(request, "auctions/listing.html", {
                        "listing": current_listing,
                        "bid_form": bid_form,
                        "comment_form": comment_form,
                        "error_message": "Bid made successfully!",
                        "is_creator": is_creator,
                        "is_in_watchlist": is_in_watchlist,
                        "highest_bidder": highest_bidder,
                        "total_bids": total_bids
                    })

                # Now setting standard if the user couldnt place high bid
                else:
                    return render(request, "auctions/listing.html", {
                        "listing": current_listing,
                        "bid_form": bid_form,
                        "comment_form": comment_form,
                        "error_message": "Bid must be higher than the current price and the highest bid",
                        "is_creator": is_creator,
                        "is_in_watchlist": is_in_watchlist,
                        "highest_bidder": highest_bidder,
                        "total_bids": total_bids
                    })
        
        # Now checking if the user submitted some kind of comment
        if "content" in request.POST:

            # Getting all the data from the post
            comment_form = CommentForm(request.POST)

            # Checking if the data was valid
            if comment_form.is_valid():

                # Temporarily saving the new comment
                new_comment = comment_form.save(commit=False)

                # Now adding required dependencies the new comment
                new_comment.commenter = request.user
                new_comment.auction = current_listing

                # Saving the data
                new_comment.save()

                return render(request, "auctions/listing.html", {
                            "listing": current_listing,
                            "bid_form": bid_form,
                            "comment_form": comment_form,
                            "error_message": "Commented Successfully",
                            "is_creator": is_creator,
                            "is_in_watchlist": is_in_watchlist,
                            "highest_bidder": highest_bidder,
                            "total_bids": total_bids
                })
    
    # If user got here through GET method

    return render(request, "auctions/listing.html", {
        "listing": current_listing,
        "bid_form": bid_form,
        "comment_form": comment_form,
        "is_creator": is_creator,
        "is_in_watchlist": is_in_watchlist,
        "highest_bidder": highest_bidder,
        "total_bids": total_bids
    }) 


@login_required(login_url="login")
def add_watchlist(request, listingID):
    req_listing = get_object_or_404(AuctionListing, pk=listingID)
    Watchlist.objects.create(user= request.user, auction= req_listing)
    return redirect("listing", listingID = req_listing.id ) # type: ignore


@login_required(login_url="login")
def remove_watchlist(request, listingID):
    req_listing = get_object_or_404(AuctionListing, pk=listingID)
    Watchlist.objects.filter(user= request.user, auction= req_listing).delete()
    return redirect("listing", listingID = req_listing.id) # type: ignore


@login_required(login_url="login")
def close_listing(request, listingID):
    req_listing = get_object_or_404(AuctionListing, pk=listingID)
    if request.user == req_listing.creator:
        req_listing.auction_active = False
        req_listing.save()
    return redirect("listing", listingID = req_listing.id) #type: ignore


@login_required(login_url="login")
def watch(request):

    # First getting all the required data loaded
    watchlist = Watchlist.objects.filter(user = request.user)
    
    # if user visited the website normally
    return render(request, "auctions/watch.html", {
        "watchlist": watchlist
    })


@login_required(login_url="login")
def category(request):

    # First getting all the required data to be loaded
    auto_form = AuctionListingForm()
    results = []

    # If user submitted my form
    if request.method == "POST":

        # Temporarily saving the data first
        selected_category = request.POST.get("category")

        # Getting the data first

Auctions_Project/auctions/templates/auctions/category.html
{% extends "auctions/layout.html" %}

{% load static %}

{% block title %}

Category

{% endblock title %}

{% block stylers %}

<link href="{% static "auctions/category.css" %}" rel="stylesheet"> 

{% endblock stylers %}

{% block body %}

    <!--Categories Header-->
    <div id="category-header-holder">
        <h1 id="category-header">Categories</h1>
    </div>

    <!--First making a panel for the user to select what kinda categories they wanna see-->
    <div id="category-holder">
        <h2 id="category-selector-header">Select a category you want to see!</h2>
        <form action="{% url "category" %}" method="post">

            {% csrf_token %}

            {{ auto_form.category }}

            <button type="submit" class="submit-button">Search</button>
        </form>
    </div>

    {% if results %}
    <!--Making an header for results-->
    <h2 id="category-results-header">Results:</h2>

    {% endif %}

    {% if results %}

        {% for result in results %}

            <ul>
                <li class="list-category"><a href="{% url "listing" result.id %}" style="text-decoration: none;"> {{ result.name }}</a> </li>
            </ul>

        {% endfor %}

    {% else %}

        <p class="error-message">No Search Results Found!</p>

    {% endif %}
{% endblock body %}

Auctions_Project/auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %}

{% block title %}

Create

{% endblock title %}

{% block body %}

    <!--Form Header-->
    <div class="form-holder">
        <h2 class="form-header">Create Listing</h2>
    </div>

    <!--FORM-->
    <form action="{% url 'create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-holder">
            <div class="form-item-holder">
                <label for="id_name" style"color: red;">Auction Name</label>
                {{ form.name }}
            </div>
            <div class="form-item-holder">
                <label for="id_price">Auction Price</label>
                {{ form.price }}
            </div>
            <div class="form-item-holder">
                <label for="id_category">Category</label>
                {{ form.category }}
            </div>
            <div class="form-item-holder">
                <label for="id_description">Description</label>
                {{ form.description }}
            </div>
            <div class="form-item-holder">
                <label for="id_pic">Add a Pic</label>
                {{ form.pic }}
            </div>
            
            <input class="submit-button" type="submit" value="Register">

        </div>
    </form>


{% endblock body %}

Auctions_Project/auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block title %}

Main

{% endblock %}

{% block body %}

    <!--AUCTION MAIN HEADER-->
    <h1 id="auction-header">Active Listings</h1>

    <!--Printing all the listings-->

    <div id="listing-holder-main">

        {% for listing in listings %}

        <div id="listing-holder">

            <!--Name of the listing header-->
            <h3 class="listing-name"><a href="{% url "listing" listing.id %}" style="text-decoration: none; color: rgb(30, 30, 156);">{{ listing.name }}</a></h3>

            <!--Creator Of the listing-->
            <p class="listing-content"><strong>Creator:</strong> {{ listing.creator }}</p>
            
            <!--Description of the listing-->
            <p class="listing-content"><strong>Details:</strong> {{ listing.description }}</p>

            <!--Price of the lisitng-->
            <p class="listing-content"><strong>Price:</strong> ${{ listing.price }}</p>

            <!--Category of the listing-->
            <p class="listing-content"><strong>Category:</strong> {{ listing.category }}</p>

            <!--Time created of the listing-->
            <p class="listing-content"><strong>Date Created:</strong> {{ listing.time }}</p>

            <!--Pic of the listing-->
            <div class="listing-pic-holder">
                {% if listing.pic %}
                    <img class="listing-pic" src="{{ listing.pic.url }}" alt="{{ listing.name }}" loading="lazy">
                {% endif %}
            </div>

        </div>

        {% endfor %}

    </div>

{% endblock %}

Auctions_Project/auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>

        <!--Meta tags for compatibillity-->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
        <!--Title of my web app made dynamic-->
        <title>Auctions: {% block title %} {% endblock %}</title>

        <!--Google Fonts-->
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,500;0,700;1,400;1,500;1,700&display=swap" rel="stylesheet">      
        <link href="https://fonts.googleapis.com/css2?family=Playwrite+HR+Lijeva&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">

        <!--Linking my own CSS file-->
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
        {% block stylers %} {% endblock %}

    </head>

    <body>

        <!--Main auctions header-->
        <h1 id="auction-header-main">Auctions</h1>
        <div>
            <div id="status-displayer-holder">

                <div class="status-displayer">
                    Status: 
                </div>

                <div class="status-displayer">
                    {% if user.is_authenticated %}
                    Signed in as <strong>{{ user.username }}</strong>.
                    {% else %}
                        Not signed in.
                    {% endif %}
                </div>
                
            </div>
        </div>

        <!--Navbar of the main page-->
        <nav id="navbar-main">

            <div class="navbar-item-holder">
                <a class="navbar-item" href="{% url 'index' %}">Active Listings</a>
            </div>

            <div class="navbar-item-holder">
                <a class="navbar-item" href="{% url "create" %}">Create Listing</a>
            </div>

            <div class="navbar-item-holder">
                <a class="navbar-item" href="{% url 'watch' %}">WatchList</a>
            </div>

            <div class="navbar-item-holder">
                <a class="navbar-item" href="{% url "category" %}">Categories</a>
            </div>

            {% if user.is_authenticated %}
                <div class="navbar-item-holder">
                    <a class="navbar-item" href="{% url 'logout' %}">Log Out</a>
                </div>
            {% else %}
                <div class="navbar-item-holder">
                    <a class="navbar-item" href="{% url 'login' %}">Log In</a>
                </div>
                <div class="navbar-item-holder">
                    <a class="navbar-item" href="{% url 'register' %}">Register</a>
                </div>
            {% endif %}

        </nav>

        <hr>
        {% block body %}
        {% endblock %}

        <!--Footer Tag of my website-->
        
        <div class="footer-main">
            <p id="footer1">@All Rights Reserved</p>
            <p id="footer2">Made by JahanZaib</p>
            <p id="footer3"><a href="https://www.djangoproject.com">Django Project</a></p>
        </div>
    </body>
</html>

Auctions_Project/auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}

{% block title %}

{{ listing.name }}

{% endblock title %}

{% block body %}

    <!--First i am gonna display rhe listing name in heading-->
    <h1 id="auction-header">Listing: {{ listing.name }}</h1>

    {% if error_message %}
        <p class="error-message">{{ error_message }}</p>
    {% endif %}

    {% if not listing.auction_active %}
        <h1 class="winner-header">LISTING CLOSED!!!</h1>
        <h2 class="winner-header">{{ highest_bidder }} Won the bid!</h2>
    {% endif %}

    <!--Now First displaying the listings pic-->
    <div class="listing-pic-holder">
        <img class="listing-pic-main" src="{{ listing.pic.url }}" alt="{{ listing.name }}">
    </div>
    
    {% if user.is_authenticated %}

        <div id="new-flexer">

            <!--Adding a watchlist button-->
            {% if is_in_watchlist %}

                <form action="{% url "remove_watchlist" listing.id %}" method="post">
                    {% csrf_token %}
                    <button id="new-button" type="submit">Remove from Watchlist</button>
                </form>

            {% else %}

                <form action="{% url "add_watchlist" listing.id %}" method="post">
                    {% csrf_token %}
                    <button id="new-button" type="submit">Add to Watchlist</button>
                </form>

            {% endif %}

            <!--Adding a Close listing button-->
            {% if is_creator %}

                <form action="{% url "close_listing" listing.id %}" method="post">
                    {% csrf_token %}
                    <button id="new-button" type="submit">Close Listing</button>
                </form>

            {% endif %}

        </div>

    {% endif %}


    <div id="list-mainer">
        <div class="listing-content-holder">

            <br><br>

            <!--Now we will be displaying details-->
            <p class="listing-content-main">{{ listing.description }}</p>

            <!--Now i will be displaying its price-->
            <h2 class="listing-content-main" style="font-size: 24px;">Starting Bid: ${{ listing.price }}</h2>

            <!--Now i will be displaying the highers BID-->
            <h2 class="listing-content-main" style="font-size: 20px;">Highest Bid: ${{ listing.highest_bid }}</h2>

            <!--Now displaying all current bids-->
            <p class="listing-content-main"> {{ total_bids }} bid(s) so far.</p>

            <div id="content-seperator"></div>

            <br><br>

            <div>
                <!--Input so user can add a new typah bid on the item-->
                <form action="{% url "listing" listing.id  %}" method="post">
                    {% csrf_token %}
                    {{ bid_form }}
                    <button id="bid-button" type="submit">Place Bid</button>
                </form>
            </div>

            <br><br>

            <div id="content-seperator"></div>

            <!--Now creating a list for its details-->
            <h2 class="listing-content-main" style="font-size: 24px">Details:</h2>

                <ul class"listing-content-list">
                    <li class="listing-list">Listed By: <strong>{{ listing.creator }}</strong></li>
                    <li class="listing-list">Highest Bidder: <strong>{{ highest_bidder }}</strong></li>
                    <li class="listing-list">Category: {{ listing.category }}</li>
                    <li class="listing-list">Date: {{ listing.time }} </li>
                    <li class="listing-list">ID Number: {{ listing.id }} </li>
                </ul>

                <br><br>

        </div>
    </div>

    <div id="comment-content-holder">

        <!--Comment Heading-->
        <h2 id="comment-header">Comments</h2>

        <!--First displaying all the availiable comments-->
        {% for comment in listing.auction_name.all %}
            <p id="comment-content"><strong>{{ comment.commenter }}:</strong> {{ comment.content }}</p>
        {% endfor %}
    </div>

    <!--Now adding the ability for users to add more comments-->
    <div id="content-data-holder">

        <!--Add Comments header-->
        <h2 id="comment-data-header">Add a Comment</h2>

        <!--Putting my form for the comments-->
        <form action="{% url "listing" listing.id %}" method="post">
            {% csrf_token %}
            {{ comment_form }}
            <button id="bid-button" type="submit">Comment</button>
        </form>

    </div>
      
{% endblock body %}

Auctions_Project/auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% load static %}

{% block title %} 

Login 

{% endblock title %}

{% block stylers %}

<link href="{% static "auctions/login.css" %}" rel="stylesheet">

{% endblock stylers %}

{% block body %}

    <div class="form-holder">
        <h2 class="form-header">Login</h2>
    </div>

    {% if message %}
        <div class="error-message">{{ message }}</div>
    {% endif %}

    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}

        <div class="form-holder">

            <div class="form-item-holder">
                <input autofocus class="form-light" type="text" name="username" placeholder="Username">
            </div>
            <div class="form-item-holder">
                <input class="form-dark" type="password" name="password" placeholder="Password">
            </div>
            <input class="submit-button" type="submit" value="Login">

        </div>
    </form>

    <div class="error-message">
        Don't have an account? <a href="{% url 'register' %}">Register here.</a>
    </div>

{% endblock %}

Auctions_Project/auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% load static %}

{% block title %}

Register

{% endblock title %}

{% block stylers %}

<link href="{% static "auctions/register.css" %}" rel="stylesheet">

{% endblock stylers %}

{% block body %}

    <div class="form-holder">
        <h2 class="form-header">Register</h2>
    </div>

    {% if message %}
        <div class="error-message">{{ message }}</div>
    {% endif %}

    <form action="{% url 'register' %}" method="post">
        {% csrf_token %}
        <div class="form-holder">

            <div class="form-item-holder">
                <input class="form-light" autofocus type="text" name="username" placeholder="Username">
            </div>
            <div class="form-item-holder">
                <input class="form-dark" type="email" name="email" placeholder="Email Address">
            </div>
            <div class="form-item-holder">
                <input class="form-light" type="password" name="password" placeholder="Password">
            </div>
            <div class="form-item-holder">
                <input class="form-dark" type="password" name="confirmation" placeholder="Confirm Password">
            </div>
            <input class="submit-button" type="submit" value="Register">

        </div>
    </form>

    <div class="error-message">
        Already have an account? <a href="{% url 'login' %}">Log In here.</a>
    </div>

{% endblock %}